[package]
name = "sr5900p"
version = "0.1.0"
edition = "2021"

[dependencies]
argh = "0.1.9"
anyhow = "1.0.66"
barcoders = "1.0.2"
embedded-graphics = "0.7.1"
png = "0.17.7"
qrcode = "0.12.0"
image = "^0.23"
regex = "1"
